### ISSUE TITLE
Capability to create a generic child pub within the GUI

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis-pl-client#9]
@bduggan we'd like to be able to create a generic child pub and associate it with a reference using the GCIS GUI.  This would allow us going forward to create "generic" pubs for references which are incorrectly categorized as articles, books, etc. within endnote.  Could we create that functionality?   @rewolfe please feel free to weigh in.   Thanks!

**Comment by bduggan** [comment]
Let's discuss this on the dev mailing list.
